swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /db/{tablename}:
    get:
      tags:
      - db
      description: 遍历指定表的所有数据
      operationId: DbController.GetAll
      parameters:
      - in: path
        name: tablename
        description: name of table
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Tablename'
    delete:
      tags:
      - db
      description: delete the Table
      operationId: DbController.Delete
      parameters:
      - in: path
        name: tablename
        description: The uid you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: tablename is empty
  /db/{tablename}/{key}:
    get:
      tags:
      - db
      description: get user by uid
      operationId: DbController.Get
      parameters:
      - in: path
        name: tablename
        description: The key for staticblock
        required: true
        type: string
      - in: path
        name: key
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Bucket'
        "403":
          description: :tablename is empty
  /db/kv:
    post:
      tags:
      - db
      description: 添加一个完整的数据 表、key、value
      operationId: DbController.CreateBucket
      parameters:
      - in: body
        name: body
        description: body for Bucket content
        required: true
        schema:
          $ref: '#/definitions/models.Bucket'
      responses:
        "200":
          description: '{int} models.Bucket.Key'
        "403":
          description: body is empty
  /db/tables:
    get:
      tags:
      - db
      description: 获取所有表的数据
      operationId: DbController.GetAllTables
      responses:
        "200":
          description: '{string} success'
    post:
      tags:
      - db
      description: 只添加表
      operationId: DbController.CreateUser
      parameters:
      - in: body
        name: body
        description: Tablename字段中只有tablename字段会被用到
        required: true
        schema:
          $ref: '#/definitions/models.Bucket'
      responses:
        "200":
          description: '{int} models.Tablename'
        "403":
          description: body is empty
  /neo4j/search:
    post:
      tags:
      - neo4j
      description: 登陆验证
      operationId: Neo4jController.Search
      parameters:
      - in: body
        name: body
        description: 查询语句
        required: true
        schema:
          $ref: '#/definitions/models.Neo4jPost'
      responses:
        "200":
          description: '{string} models.Neo4jPost.Cql'
        "403":
          description: body is empty
definitions:
  models.Bucket:
    title: Bucket
    type: object
    properties:
      key:
        type: string
      tablename:
        type: string
      value:
        type: string
  models.Neo4jPost:
    title: Neo4jPost
    type: object
    properties:
      cql:
        type: string
  models.Tablename:
    title: Tablename
    type: object
tags:
- name: neo4j
  description: |
    后端系统认证
- name: db
  description: |
    Operations about Bucket
